//------------------------------------------------------------------------
// Copyright(c) 2024 Noah Dominic.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"NSImpleClipper.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"NSImpleClipper VST3 (64Bit)"
#else
#define stringFileDescription	"NSImpleClipper VST3"
#endif
#define stringCompanyName		"Noah Dominic\0"
#define stringLegalCopyright	"Copyright(c) 2024 Noah Dominic."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
